//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kuryeGozlemTakip
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courier
    {
        public string Ad { get; set; }
        public string İkinci_Ad { get; set; }
        public string Soyad { get; set; }
        public string Kart_No { get; set; }
        public string İşlem_Kodu { get; set; }
        public string Kurye_Kodu { get; set; }
        public string Kaynak_Kodu { get; set; }
        public string Kart_Turu { get; set; }
        public Nullable<System.DateTime> Kayıt_Tarihi { get; set; }
        public Nullable<System.DateTime> Teslim_Tarihi { get; set; }
        public Nullable<System.DateTime> Kurye_Veriliş_Tarihi { get; set; }
        public string Bs_Müşteri_No { get; set; }
        public string Vb_Müşteri_No { get; set; }
        public string Barkod { get; set; }
        public string Tc_Kimlik_No { get; set; }
        public string Şube_Kodu { get; set; }
        public string Ürün_Kodu { get; set; }
        public string Bayi_Kodu { get; set; }
        public string Sözleşmesi__Var { get; set; }
        public Nullable<System.DateTime> Basım_Tarihi { get; set; }
        public Nullable<System.DateTime> İade_Tarihi { get; set; }
    }
}
